name: XLTournaments
version: '${version}'
authors: [ItsLewizzz, ItzSave]
main: net.zithium.tournaments.XLTournamentsPlugin
api-version: 1.20
softdepend: [Vault, PlaceholderAPI]

commands:
  tournament:
    description: Main command.